import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        justifyContent: "space-between",
        height: "100%",
        backgroundColor: "#F5F7F9",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingTop: 50,
        paddingVertical: 25,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: "#F0F0F0",
    },
    backButton: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: "#F5F7F9",
        justifyContent: "center",
        alignItems: "center",
    },
    backArrow: {
        transform: [{ rotate: "180deg" }],
    },
    headerTitle: {
        fontSize: 17,
        fontWeight: "600",
        color: "#1C2229",
    },
    headerRight: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: "#F5F7F9",
        justifyContent: "center",
        alignItems: "center",
    },
    scrollViewContainer: {
        justifyContent: "center",
        alignItems: "center",
        marginTop: 5,
        backgroundColor: "transparent",
        gap: 10,
    },
    scrollView: {
        height: "62%",
        marginBottom: 65,
    },
    cartItemsContainer: {
        flexDirection: "column",
        flexWrap: "wrap",
        gap: 10,
        backgroundColor: "transparent",
    },
    checkoutCard: {
        width: "100%",
        height: 170,
        backgroundColor: "#fff",
        flexDirection: "column",
        justifyContent: "space-between",
        alignItems: "flex-end",
        padding: 20,
        top: -60,
        marginBottom: 28,
        borderRadius: 20,
    },
    voucherRow: {
        backgroundColor: "#EFF7ED",
        width: "100%",
        height: 56,
        marginBottom: 20,
        borderRadius: 20,
        borderColor: "#457B37",
        borderWidth: 1,
        justifyContent: "space-between",
        paddingHorizontal: 20,
        flexDirection: "row",
        alignItems: "center",
        gap: 20,
    },
    voucherRowInner: {
        backgroundColor: "transparent",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 10,
    },
    voucherText: {
        fontSize: 14,
        color: "#457B37",
    },
    totalRow: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-end",
    },
    totalLabel: {
        fontSize: 12,
        color: "#B9BABD",
        fontWeight: "400",
    },
    totalPrice: {
        fontSize: 24,
        fontWeight: "600",
        color: "#1C2229",
    },
    checkoutButton: {
        width: 150,
        height: 50,
        backgroundColor: "#61AD4E",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    checkoutButtonText: {
        color: "#fff",
        fontSize: 14,
    },
});
