import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    container: {
        justifyContent: "space-between",
        height: "100%",
        backgroundColor: "#F5F7F9",
    },
    header: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        paddingHorizontal: 16,
        paddingTop: 50,
        paddingVertical: 25,
        backgroundColor: "#fff",
        borderBottomWidth: 1,
        borderBottomColor: "#F0F0F0",
    },
    backButton: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: "#F5F7F9",
        justifyContent: "center",
        alignItems: "center",
    },
    backArrow: {
        transform: [{ rotate: "180deg" }],
    },
    headerTitle: {
        fontSize: 17,
        fontWeight: "600",
        color: "#1C2229",
    },
    headerRight: {
        width: 36,
        height: 36,
        borderRadius: 12,
        backgroundColor: "#FCE9E9",
        justifyContent: "center",
        alignItems: "center",
    },
    headerRightActive: {
        backgroundColor: "#E33434",
    },
    scrollViewContainer: {
        justifyContent: "center",
        alignItems: "center",
        marginTop: 10,
        backgroundColor: "transparent",
        gap: 10,
    },
    scrollView: {
        height: "62%",
        marginBottom: 75,
    },
    scrollViewDelete: {
        height: "66%",
        marginBottom: 65,
    },
    cartItemsContainer: {
        flexDirection: "column",
        flexWrap: "wrap",
        gap: 10,
        backgroundColor: "transparent",
    },
    bottomCard: {
        width: "100%",
        height: 170,
        backgroundColor: "#fff",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: 20,
        top: -65,
        marginBottom: 28,
        borderRadius: 20,
    },
    bottomCardDelete: {
        width: "100%",
        height: 140,
        backgroundColor: "#fff",
        flexDirection: "column",
        justifyContent: "space-between",
        padding: 20,
        top: -60,
        marginBottom: 28,
        borderRadius: 20,
    },
    bottomCardCheckout: {
        alignItems: "flex-end",
    },
    selectAllRow: {
        flexDirection: "row",
        alignItems: "center",
        gap: 12,
    },
    checkbox: {
        width: 22,
        height: 22,
        borderRadius: 6,
        borderWidth: 2,
        borderColor: "#B9BABD",
        backgroundColor: "#fff",
        justifyContent: "center",
        alignItems: "center",
    },
    checkboxSelected: {
        backgroundColor: "#61AD4E",
        borderColor: "#61AD4E",
    },
    selectAllText: {
        fontSize: 14,
        fontWeight: "500",
        color: "#1C2229",
    },
    deleteButton: {
        width: "100%",
        height: 50,
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    deleteButtonActive: {
        backgroundColor: "#E33434",
    },
    deleteButtonDisabled: {
        backgroundColor: "#E0E0E0",
    },
    deleteButtonText: {
        fontSize: 14,
        fontWeight: "600",
    },
    deleteButtonTextActive: {
        color: "#fff",
    },
    deleteButtonTextDisabled: {
        color: "#999",
    },
    voucherRow: {
        backgroundColor: "#EFF7ED",
        width: "100%",
        height: 56,
        marginBottom: 20,
        borderRadius: 20,
        borderColor: "#457B37",
        borderWidth: 1,
        justifyContent: "space-between",
        paddingHorizontal: 20,
        flexDirection: "row",
        alignItems: "center",
        gap: 20,
    },
    voucherRowInner: {
        backgroundColor: "transparent",
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        gap: 10,
    },
    voucherText: {
        fontSize: 14,
        color: "#457B37",
    },
    totalRow: {
        width: "100%",
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "flex-end",
    },
    totalLabel: {
        fontSize: 12,
        color: "#B9BABD",
        fontWeight: "400",
    },
    totalPrice: {
        fontSize: 24,
        fontWeight: "600",
        color: "#1C2229",
    },
    checkoutButton: {
        width: 150,
        height: 50,
        backgroundColor: "#61AD4E",
        borderRadius: 10,
        alignItems: "center",
        justifyContent: "center",
    },
    checkoutButtonText: {
        color: "#fff",
        fontSize: 14,
    },
});
